// ==UserScript==
// @name         Relay Agent for DeepSeek
// @namespace    relay-agent-local
// @version      0.7.0
// @description  Relay Agent：在 DeepSeek 网页与本地工具运行时之间建立受控的 JavaScript 工具闭环。
// @match        https://chat.deepseek.com/*
// @run-at       document-idle
// @grant        GM_xmlhttpRequest
// @connect      127.0.0.1
// @connect      localhost
// ==/UserScript==

(() => {
'use strict';
if (window.__RELAY_AGENT_V7__) return;
window.__RELAY_AGENT_V7__ = true;

const CFG={apiBase:'http://127.0.0.1:8899',maxLogs:500,panelW:620,panelH:650,replyDebounce:1300,maxLoopSteps:30,sendDelayMin:2000,sendDelayMax:4000};
const SKEY={w:'cuckoo-v6-w',h:'cuckoo-v6-h',x:'cuckoo-v6-x',y:'cuckoo-v6-y',api:'cuckoo-v6-api',key:'cuckoo-v6-session-key'};
const WHALE = '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill="none" stroke="#4d6bfe" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M4 7h12m0 0-3-3m3 3-3 3M20 17H8m0 0 3-3m-3 3 3 3"/><circle cx="4" cy="7" r="2" fill="#4d6bfe"/><circle cx="20" cy="17" r="2" fill="#4d6bfe"/></svg>';

const CSS = `
#cuckoo-fab,#cuckoo-panel,#cuckoo-toast,#cuckoo-modal{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif!important;box-sizing:border-box!important;color:#17191f!important}
#cuckoo-fab *,#cuckoo-panel *,#cuckoo-toast *,#cuckoo-modal *{box-sizing:border-box!important}
#cuckoo-fab{position:fixed!important;right:24px;bottom:24px;width:58px;height:58px;border-radius:19px!important;background:rgba(255,255,255,.94)!important;border:1px solid rgba(15,23,42,.11)!important;box-shadow:0 14px 42px rgba(15,23,42,.16)!important;z-index:2147483647!important;display:grid!important;place-items:center!important;cursor:grab!important;user-select:none!important;touch-action:none!important;backdrop-filter:blur(18px)!important}
#cuckoo-fab svg{width:34px;height:34px!important}#cuckoo-fab-dot{position:absolute!important;right:5px;top:5px;width:9px;height:9px;border-radius:50%!important;background:#a3a8b2!important;border:2px solid #fff!important}#cuckoo-fab-dot.on{background:#22a06b!important}#cuckoo-fab-dot.run{background:#f59e0b!important;animation:cuckoo-pulse 1s infinite!important}@keyframes cuckoo-pulse{50%{opacity:.35}}
#cuckoo-panel{--bg:#fbfbfc;--card:#fff;--soft:#f4f5f7;--line:#e6e8ec;--text:#17191f;--muted:#747b8a;--blue:#4d6bfe;position:fixed!important;width:620px;height:650px;min-width:420px;min-height:420px;background:rgba(251,251,252,.985)!important;border:1px solid rgba(15,23,42,.10)!important;border-radius:22px!important;box-shadow:0 30px 90px rgba(15,23,42,.22)!important;z-index:2147483646!important;overflow:hidden!important;backdrop-filter:blur(26px)!important;transition:opacity .16s ease,transform .16s ease!important}
#cuckoo-panel.hide{opacity:0!important;transform:translateY(8px) scale(.99)!important;pointer-events:none!important}
#cuckoo-shell{display:grid!important;grid-template-columns:88px 1fr!important;height:100%!important}
#cuckoo-rail{background:#f4f5f8!important;border-right:1px solid var(--line)!important;padding:14px 9px!important;display:flex!important;flex-direction:column!important;gap:6px!important}
#cuckoo-brand{height:57px!important;display:grid!important;place-items:center!important;margin-bottom:5px!important}#cuckoo-brand svg{width:29px;height:29px!important}.cuckoo-nav{border:0!important;background:transparent!important;border-radius:11px!important;padding:9px 7px!important;font-size:11px!important;color:#737987!important;font-weight:650!important;cursor:pointer!important;text-align:center!important}.cuckoo-nav:hover{background:#e9ebf0!important;color:#222!important}.cuckoo-nav.active{background:#fff!important;color:#20232a!important;box-shadow:0 1px 4px rgba(15,23,42,.08)!important}
#cuckoo-main{display:grid!important;grid-template-rows:68px 1fr 34px!important;min-width:0!important;min-height:0!important}
#cuckoo-head{padding:13px 17px 10px!important;border-bottom:1px solid var(--line)!important;display:flex!important;justify-content:space-between!important;align-items:center!important;gap:12px!important}.cuckoo-headtitle{font-weight:780!important;font-size:15px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}.cuckoo-sub{font-size:10.5px!important;color:var(--muted)!important;margin-top:2px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;max-width:360px!important}.cuckoo-status{display:flex!important;gap:5px!important;align-items:center!important;font-size:10px!important;color:var(--muted)!important}.cuckoo-dot{width:7px;height:7px;border-radius:50%!important;background:#a3a8b2!important}.cuckoo-dot.on{background:#22a06b!important}.cuckoo-dot.run{background:#f59e0b!important}
#cuckoo-view{overflow:auto!important;padding:14px 16px!important;min-height:0!important}#cuckoo-foot{border-top:1px solid var(--line)!important;display:flex!important;align-items:center!important;gap:11px!important;padding:0 14px!important;font-size:9.5px!important;color:#7c8494!important;white-space:nowrap!important;overflow:hidden!important}.cuckoo-cap{display:flex!important;align-items:center!important;gap:4px!important}.cuckoo-cap i{width:6px;height:6px;border-radius:50%!important;background:#aeb3bd!important}.cuckoo-cap.ok i{background:#22a06b!important}
.cuckoo-section-title{font-size:11px!important;font-weight:760!important;color:#666d7b!important;text-transform:uppercase!important;letter-spacing:.04em!important;margin:3px 0 8px!important}.cuckoo-card{background:var(--card)!important;border:1px solid var(--line)!important;border-radius:14px!important;padding:12px!important;margin-bottom:10px!important;box-shadow:0 1px 2px rgba(15,23,42,.025)!important}.cuckoo-row{display:flex!important;gap:7px!important;align-items:center!important;flex-wrap:wrap!important}.cuckoo-spread{display:flex!important;gap:8px!important;align-items:center!important;justify-content:space-between!important}.cuckoo-muted{color:var(--muted)!important;font-size:10.5px!important}.cuckoo-code{font:10.5px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace!important;background:#f6f7f9!important;border:1px solid #eceef1!important;border-radius:10px!important;padding:9px!important;white-space:pre-wrap!important;word-break:break-word!important;max-height:220px!important;overflow:auto!important;color:#343944!important}
.cuckoo-btn{border:1px solid #e2e5e9!important;background:#fff!important;color:#30343b!important;border-radius:9px!important;padding:7px 9px!important;font-size:10.5px!important;font-weight:680!important;cursor:pointer!important;box-shadow:0 1px 1px rgba(15,23,42,.02)!important}.cuckoo-btn:hover{background:#f7f8fa!important}.cuckoo-btn.primary{background:#4d6bfe!important;border-color:#4d6bfe!important;color:#fff!important}.cuckoo-btn.danger{color:#b42318!important;background:#fff5f5!important;border-color:#fed7d7!important}.cuckoo-btn:disabled{opacity:.45!important;cursor:default!important}.cuckoo-input,.cuckoo-textarea{width:100%!important;border:1px solid #dfe2e7!important;background:#fff!important;color:#222!important;border-radius:10px!important;padding:8px 9px!important;font-size:11px!important;outline:none!important}.cuckoo-input:focus,.cuckoo-textarea:focus{border-color:#9eb0ff!important;box-shadow:0 0 0 3px rgba(77,107,254,.08)!important}.cuckoo-textarea{min-height:80px!important;resize:vertical!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important}
.cuckoo-pill{font-size:9.5px!important;border-radius:99px!important;padding:3px 6px!important;background:#f0f2f5!important;color:#686f7d!important}.cuckoo-pill.green{background:#eaf8f1!important;color:#18794e!important}.cuckoo-pill.amber{background:#fff6df!important;color:#8a5b00!important}.cuckoo-pill.red{background:#fff0f0!important;color:#b42318!important}
.cuckoo-diag{display:grid!important;grid-template-columns:92px 1fr!important;gap:7px 10px!important;font-size:10.5px!important;align-items:center!important}.cuckoo-diag .k{color:var(--muted)!important}.cuckoo-diag .v{font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;word-break:break-all!important}.cuckoo-strong-ok{color:#18794e!important;font-weight:750!important}.cuckoo-strong-warn{color:#8a5b00!important;font-weight:750!important}.cuckoo-strong-err{color:#b42318!important;font-weight:750!important}
.cuckoo-event{display:grid!important;grid-template-columns:18px 1fr!important;gap:8px!important;margin-bottom:7px!important}.cuckoo-eventline{position:relative!important;display:flex!important;justify-content:center!important}.cuckoo-eventline:after{content:"";position:absolute!important;top:13px;bottom:-11px;width:1px;background:#e4e7eb!important}.cuckoo-event:last-child .cuckoo-eventline:after{display:none!important}.cuckoo-eventdot{width:8px;height:8px;border-radius:50%!important;background:#a9afba!important;margin-top:7px!important;z-index:1!important}.cuckoo-eventdot.ok{background:#22a06b!important}.cuckoo-eventdot.run{background:#f59e0b!important}.cuckoo-eventdot.err{background:#e5484d!important}.cuckoo-eventbody{background:#fff!important;border:1px solid #e7e9ed!important;border-radius:12px!important;padding:9px 10px!important;min-width:0!important}.cuckoo-eventtitle{font-size:11px!important;font-weight:720!important}.cuckoo-eventmeta{font-size:9.5px!important;color:#8a919f!important;margin-top:2px!important}.cuckoo-eventout{font:10px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace!important;margin-top:7px!important;white-space:pre-wrap!important;word-break:break-word!important;color:#454b57!important;max-height:170px!important;overflow:auto!important}
.cuckoo-file{display:flex!important;justify-content:space-between!important;gap:8px!important;padding:7px 8px!important;border-radius:8px!important;font-size:10.5px!important;cursor:default!important}.cuckoo-file:hover{background:#f5f6f8!important}.cuckoo-log{font:10px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace!important;white-space:pre-wrap!important;word-break:break-word!important;padding:2px 0!important;color:#4d5360!important}.cuckoo-log.err{color:#c13737!important}.cuckoo-log.ok{color:#18794e!important}
#cuckoo-resize{position:absolute!important;width:24px;height:24px;right:0;bottom:0;cursor:nwse-resize!important;touch-action:none!important}#cuckoo-resize:after{content:"";position:absolute;right:6px;bottom:6px;width:7px;height:7px;border-right:1.5px solid #9ca3af;border-bottom:1.5px solid #9ca3af}
#cuckoo-toast{position:fixed!important;top:22px;right:22px;z-index:2147483647!important;display:flex!important;flex-direction:column!important;gap:6px!important}.cuckoo-toastitem{background:#20232a!important;color:#fff!important;border-radius:10px!important;padding:8px 10px!important;font-size:10.5px!important;box-shadow:0 10px 30px rgba(0,0,0,.2)!important;max-width:360px!important}.cuckoo-toastitem.err{background:#8f2626!important}.cuckoo-toastitem.ok{background:#176b47!important}
#cuckoo-modal{position:fixed!important;inset:0!important;background:rgba(20,24,32,.28)!important;z-index:2147483647!important;display:grid!important;place-items:center!important}#cuckoo-modal.hide{display:none!important}#cuckoo-modalbox{width:min(500px,calc(100vw - 32px));background:#fff!important;border-radius:16px!important;border:1px solid #e2e5e9!important;box-shadow:0 30px 80px rgba(0,0,0,.25)!important;padding:15px!important}.cuckoo-modal-title{font-weight:780!important;font-size:13px!important;margin-bottom:5px!important}
`;

const HTML = `
<div id="cuckoo-fab" title="Relay Agent">${WHALE}<span id="cuckoo-fab-dot"></span></div>
<div id="cuckoo-panel"><div id="cuckoo-shell">
<aside id="cuckoo-rail"><div id="cuckoo-brand">${WHALE}</div>
<button id="cuckoo-nav-agent" class="cuckoo-nav active" data-tab="agent">智能体</button>
<button id="cuckoo-nav-files" class="cuckoo-nav" data-tab="files">项目</button>
<button id="cuckoo-nav-tools" class="cuckoo-nav" data-tab="tools">工具</button>
<button id="cuckoo-nav-plugins" class="cuckoo-nav" data-tab="plugins">插件</button>
<button id="cuckoo-nav-logs" class="cuckoo-nav" data-tab="logs">日志</button>
<button id="cuckoo-nav-settings" class="cuckoo-nav" data-tab="settings">设置</button>
</aside>
<main id="cuckoo-main"><header id="cuckoo-head"><div><div id="cuckoo-headtitle" class="cuckoo-headtitle">Relay Agent</div><div id="cuckoo-headsub" class="cuckoo-sub">cuckoo JavaScript + 本地运行时</div></div><div class="cuckoo-status"><i id="cuckoo-head-dot" class="cuckoo-dot"></i><span id="cuckoo-head-status">未连接</span></div></header><section id="cuckoo-view"></section><footer id="cuckoo-foot"></footer></main>
</div><div id="cuckoo-resize"></div></div>
<div id="cuckoo-toast"></div>
<div id="cuckoo-modal" class="hide"><div id="cuckoo-modalbox"><div id="cuckoo-modal-title" class="cuckoo-modal-title">执行审批</div><div id="cuckoo-modal-text" class="cuckoo-code"></div><div class="cuckoo-row" style="margin-top:10px"><button id="cuckoo-modal-deny" class="cuckoo-btn danger">拒绝</button><button id="cuckoo-modal-once" class="cuckoo-btn primary">本次允许</button><button id="cuckoo-modal-trust" class="cuckoo-btn">信任此项目中的相同命令</button></div></div></div>`;

const state={
 open:true,tab:'agent',apiBase:localStorage.getItem(SKEY.api)||CFG.apiBase,apiKey:sessionStorage.getItem(SKEY.key)||'',
 reachable:false,authenticated:false,transport:'未检测',agentVersion:'-',agentPid:null,latencyMs:null,lastCheck:null,lastError:'尚未检测',
 webBridgeOnline:false,webBridgeQueued:0,webBridgeBusy:false,webClientId:'web_'+cryptoToken(),
 agentTools:[],plugins:[],projectRoot:'',logs:[],timeline:[],initialized:false,loopEnabled:true,loopBusy:false,loopSteps:0,
 currentJsRunId:null,sessionId:'sess_web_'+Date.now().toString(36),scanTimer:0,lastNode:null,lastText:'',lastChangedAt:0,xmlHintCount:0,
 processedResponses:new Set(),activeWebChat:null,modalBusy:false,sendQueue:Promise.resolve(),sendQueued:0,lastSendAt:0
};

const $=id=>document.getElementById(id);
function cryptoToken(){const a=new Uint8Array(8);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('');}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=o=>{try{return JSON.stringify(o,null,2)}catch{return String(o)}};
function hashText(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)+':'+s.length;}
function log(msg,type='info'){const t=new Date().toLocaleTimeString([],{hour12:false});state.logs.push({t,msg:String(msg),type});if(state.logs.length>CFG.maxLogs)state.logs.shift();console[type==='err'?'error':'log']('[Relay]',msg);if(state.tab==='logs')render();}
function toast(msg,type=''){const e=document.createElement('div');e.className='cuckoo-toastitem '+type;e.textContent=msg;$('cuckoo-toast').appendChild(e);setTimeout(()=>e.remove(),3200);}
function addEvent(kind,title,meta='',output='',status=''){const e={id:'ev_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),kind,title,meta,output,status,ts:Date.now()};state.timeline.push(e);if(state.timeline.length>140)state.timeline.shift();if(state.tab==='agent')render();return e;}
function patchEvent(id,p){const e=state.timeline.find(x=>x.id===id);if(e)Object.assign(e,p);if(state.tab==='agent')render();}
function inject(){const style=document.createElement('style');style.id='cuckoo-style';style.textContent=CSS;document.head.appendChild(style);document.body.insertAdjacentHTML('beforeend',HTML);}
function setHeader(title,sub){$('cuckoo-headtitle').textContent=title;$('cuckoo-headsub').textContent=sub;}
function connectionText(){if(state.loopBusy)return '正在执行';if(state.authenticated)return '已连接';if(state.reachable)return state.apiKey?'鉴权失败':'后台可达';return '未连接';}
function setStatus(){const d=$('cuckoo-fab-dot'),h=$('cuckoo-head-dot');d.className='';h.className='cuckoo-dot';if(state.loopBusy){d.classList.add('run');h.classList.add('run')}else if(state.authenticated){d.classList.add('on');h.classList.add('on')}else if(state.reachable){d.classList.add('run');h.classList.add('run')}$('cuckoo-head-status').textContent=connectionText();renderFoot();}
function renderFoot(){const e=$('cuckoo-foot');if(!e)return;e.innerHTML=`<span class="cuckoo-cap ${state.authenticated?'ok':''}"><i></i>Agent ${state.authenticated?'已连接':state.reachable?'待鉴权':'离线'}</span><span class="cuckoo-cap ${state.webBridgeOnline?'ok':''}"><i></i>网页桥 ${state.webBridgeOnline?'在线':'离线'}</span><span class="cuckoo-cap ${state.initialized?'ok':''}"><i></i>cuckoo 协议 ${state.initialized?'已初始化':'未初始化'}</span><span class="cuckoo-cap"><i></i>${esc(state.projectRoot?state.projectRoot.split('/').filter(Boolean).at(-1):'未设项目')}</span>`;}
function parseApiResponse(status,text){let d={};try{d=text?JSON.parse(text):{}}catch{d={raw:text}};d.__status=status;if(status<200||status>=300){const e=new Error(d.error||`HTTP ${status}`);e.status=status;e.data=d;throw e}return d;}
function gmApiRequest(url,opt,headers){return new Promise((resolve,reject)=>{if(typeof GM_xmlhttpRequest!=='function')return reject(Object.assign(new Error('GM_xmlhttpRequest 不可用'),{transportUnavailable:true}));GM_xmlhttpRequest({method:opt.method||'GET',url,headers,data:opt.body===undefined?undefined:JSON.stringify(opt.body),timeout:opt.timeout||15000,onload:r=>{try{resolve(parseApiResponse(r.status,r.responseText||''))}catch(e){reject(e)}},onerror:()=>reject(new Error('Tampermonkey 无法连接本地 Agent')),ontimeout:()=>reject(new Error('请求超时'))})})}
async function fetchApiRequest(url,opt,headers){const c=new AbortController(),timer=setTimeout(()=>c.abort(),opt.timeout||15000);try{const r=await fetch(url,{method:opt.method||'GET',headers,body:opt.body===undefined?undefined:JSON.stringify(opt.body),signal:c.signal,cache:'no-store',credentials:'omit'});return parseApiResponse(r.status,await r.text())}catch(e){if(e.name==='AbortError')throw new Error('请求超时');throw e}finally{clearTimeout(timer)}}
async function api(pathname,opt={}){const headers={'Content-Type':'application/json'};if(opt.auth!==false){if(!state.apiKey)throw new Error('未设置 API Key');headers['X-API-Key']=state.apiKey}const url=state.apiBase.replace(/\/$/,'')+pathname;try{const d=await gmApiRequest(url,opt,headers);state.transport='Tampermonkey';return d}catch(gmErr){if(gmErr.status)throw gmErr;try{const d=await fetchApiRequest(url,opt,headers);state.transport='浏览器 fetch';return d}catch(fetchErr){fetchErr.message=`${gmErr.message}；fetch: ${fetchErr.message}`;throw fetchErr}}}
async function heartbeatBridge(){if(!state.authenticated)return false;const d=await api('/api/web/heartbeat',{method:'POST',body:{clientId:state.webClientId,pageUrl:location.href,title:document.title,assistantCount:assistantNodes().length},timeout:3000});state.webBridgeOnline=!!d.online;return true;}
async function refreshAgent(silent=true){const started=performance.now();state.lastCheck=new Date().toLocaleTimeString([],{hour12:false});state.lastError='';try{const s=await api('/api/status',{auth:false,timeout:2500});state.reachable=s.status==='running';state.agentVersion=s.version||'-';state.agentPid=s.pid||null;state.latencyMs=Math.round(performance.now()-started);state.authenticated=false;state.agentTools=[];if(state.reachable&&state.apiKey){try{const [t,p,c]=await Promise.all([api('/api/tools',{timeout:3500}),api('/api/plugins',{timeout:3500}).catch(()=>({plugins:[]})),api('/api/config',{timeout:3500})]);state.agentTools=t.tools||[];state.plugins=p.plugins||[];state.projectRoot=c.config?.projectRoot||'';state.authenticated=true;await heartbeatBridge().catch(()=>{});const wb=await api('/api/web/status',{timeout:3000}).catch(()=>null);state.webBridgeOnline=!!wb?.online;state.webBridgeQueued=wb?.queued||0;}catch(e){state.lastError=e.status===401?'API Key 错误或已失效':e.message;state.webBridgeOnline=false}}else if(state.reachable&&!state.apiKey)state.lastError='后台已运行，但尚未填写本机 API Key';setStatus();if(!silent)toast(state.authenticated?'本地 Agent 已连接':state.reachable?'找到 Agent，但尚未认证':'Agent 未连接',state.authenticated?'ok':'');return s}catch(e){state.reachable=false;state.authenticated=false;state.agentTools=[];state.lastError=e.message||String(e);state.webBridgeOnline=false;setStatus();if(!silent)toast('本地 Agent 未连接: '+state.lastError,'err');return null}}
async function recordSession(type,data){if(!state.authenticated)return;try{await api(`/api/sessions/${encodeURIComponent(state.sessionId)}/events`,{method:'POST',body:{type,data},timeout:4000})}catch{}}

function assistantNodes(){return [...document.querySelectorAll('.ds-markdown')].filter(n=>!n.closest('#cuckoo-panel')&&!n.closest('#cuckoo-modal'));}
function assistantText(node){return String(node?.innerText||node?.textContent||'').trim();}
function findComposer(){return document.querySelector('textarea')||document.querySelector('[contenteditable="true"][role="textbox"]')||document.querySelector('[contenteditable="true"]');}
function setComposer(el,text){if(el instanceof HTMLTextAreaElement){const s=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set;s.call(el,text);el.dispatchEvent(new Event('input',{bubbles:true}))}else{el.focus();document.execCommand('selectAll',false);document.execCommand('insertText',false,text);el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}))}}
function randomSendDelay(){return Math.floor(CFG.sendDelayMin+Math.random()*(CFG.sendDelayMax-CFG.sendDelayMin+1));}
async function sendDeepSeekNow(text,delayMs){
 const waitMs=delayMs??randomSendDelay();
 addEvent('bridge','消息排队',`将在 ${(waitMs/1000).toFixed(1)} 秒后发送到 DeepSeek`,String(text).slice(0,220),'run');
 await new Promise(r=>setTimeout(r,waitMs));
 const el=findComposer();if(!el)throw new Error('找不到 DeepSeek 输入框');
 setComposer(el,text);el.focus();await new Promise(r=>setTimeout(r,160));
 el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));
 el.dispatchEvent(new KeyboardEvent('keyup',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));
 state.lastSendAt=Date.now();
 log(`发送到 DeepSeek（延迟 ${waitMs}ms）: `+String(text).slice(0,140));
}
function sendDeepSeek(text){
 const payload=String(text);state.sendQueued++;setStatus();
 const job=state.sendQueue.catch(()=>{}).then(()=>sendDeepSeekNow(payload));
 state.sendQueue=job.finally(()=>{state.sendQueued=Math.max(0,state.sendQueued-1);setStatus();});
 return state.sendQueue;
}
function getCodeBlockLanguage(pre){if(!pre)return'';let lang=pre.getAttribute('data-language')||'';if(!lang){const pd=pre.closest('div[data-language]');if(pd)lang=pd.getAttribute('data-language')||''}if(!lang){const code=pre.querySelector('code');for(const el of [code,pre].filter(Boolean)){const c=[...el.classList].find(x=>x.startsWith('language-'));if(c){lang=c.slice(9);break}}}if(!lang){const block=pre.closest('.md-code-block');const banner=block?.querySelector('.md-code-block-banner');if(banner){for(const span of banner.querySelectorAll('span')){if(span.closest('button'))continue;const t=(span.textContent||'').trim();if(/^[a-zA-Z0-9_+#.-]{1,20}$/.test(t)){lang=t;break}}}}return String(lang||'').toLowerCase();}
function syntaxComplete(code){try{new Function('return (async()=>{\n'+code+'\n});');return true}catch{return false}}
function cuckooPres(root){return root?[...root.querySelectorAll('pre')].filter(pre=>getCodeBlockLanguage(pre)==='cuckoo'):[]}
function extractCuckooBlocks(root){const out=[];for(const pre of cuckooPres(root)){const code=((pre.querySelector('code')||pre).textContent||'').trim();if(code&&syntaxComplete(code))out.push(code)}return out;}
function latestStableAssistant(){const nodes=assistantNodes();const node=nodes.at(-1);if(!node)return null;const text=assistantText(node);if(node!==state.lastNode||text!==state.lastText){state.lastNode=node;state.lastText=text;state.lastChangedAt=Date.now();return null}if(!text||Date.now()-state.lastChangedAt<CFG.replyDebounce)return null;return {node,text,count:nodes.length,key:hashText(text+'|'+extractCuckooBlocks(node).join('\n---\n'))};}


function detectXmlToolCall(text){
 const t=String(text||'').trim();
 const hasDsml=/^<\s*｜｜DSML｜｜/i.test(t);
 const hasInvoke=/^<\s*(?:[\w-]+:)?invoke\s+name=/i.test(t);
 const hasClose=/<\s*\/\s*(?:[\w-]+:)?invoke\s*>/i.test(t);
 const hasParam=/<\s*(?:[\w-]+:)?parameter\s+name=/i.test(t);
 return hasDsml||(hasInvoke&&(hasClose||hasParam));
}
function parseJsonToolCall(text){
 const t=String(text||'').trim(); if(!t.startsWith('{')||!t.endsWith('}'))return null;
 try{const o=JSON.parse(t);const tool=String(o.toolName||o.tool||'');if(!tool)return null;return {tool,arguments:o.arguments||o.params||o.input||{},callId:o.callId||o.id||''}}catch{return null}
}
async function executeJsonToolCall(tc,responseKey){
 state.loopBusy=true;setStatus();try{state.processedResponses.add(responseKey);const ev=addEvent('tool',`兼容 JSON 工具 · ${tc.tool}`,'发送到 Agent',fmt(tc.arguments),'run');const d=await api('/api/execute',{method:'POST',body:{tool:tc.tool,arguments:tc.arguments||{},sessionId:state.sessionId},timeout:8000});let c=d.call;if(c?.status==='waiting_approval'){await checkApprovals()}const started=Date.now();while(c&&!['completed','failed','cancelled'].includes(c.status)&&Date.now()-started<360000){await checkApprovals();await new Promise(r=>setTimeout(r,350));c=(await api(`/api/calls/${encodeURIComponent(c.id)}`)).call}const ok=c?.status==='completed';patchEvent(ev.id,{status:ok?'ok':'err',meta:c?.status||'failed',output:fmt(ok?c.result:c?.error)});await sendDeepSeek(`【Relay JSON 兼容工具结果】\n${ok?'✅ 成功':'❌ 失败'}\n工具: ${tc.tool}\n${fmt(ok?c.result:c?.error)}\n\n后续工具调用请改用完整的 \`\`\`cuckoo JavaScript 代码块。`)}finally{state.loopBusy=false;setStatus()}
}

let modalResolve=null,modalApproval=null;
function showApproval(a){if(state.modalBusy)return null;state.modalBusy=true;modalApproval=a;$('cuckoo-modal-title').textContent=`审批 · ${a.tool}`;$('cuckoo-modal-text').textContent=`${a.reason||'需要确认'}\n\n${fmt(a.args)}`;$('cuckoo-modal-trust').style.display=a.tool==='shell'?'inline-block':'none';$('cuckoo-modal').classList.remove('hide');return new Promise(r=>modalResolve=r)}
function closeApproval(decision){$('cuckoo-modal').classList.add('hide');const r=modalResolve,a=modalApproval;modalResolve=null;modalApproval=null;state.modalBusy=false;if(r)r({decision,a})}
async function checkApprovals(){if(!state.authenticated||state.modalBusy)return;try{const d=await api('/api/approvals',{timeout:2500});const a=(d.approvals||[])[0];if(!a)return;const x=await showApproval(a);if(x?.a)await api(`/api/approvals/${encodeURIComponent(x.a.id)}/decision`,{method:'POST',body:{decision:x.decision},timeout:4000})}catch(e){log('审批检查: '+e.message,'err')}}

async function startJsRun(code,index,total){const ev=addEvent('cuckoo',`执行 cuckoo 脚本 ${index}/${total}`,'发送到本地 Agent',code.slice(0,1800),'run');const d=await api('/api/js-runs',{method:'POST',body:{code,sessionId:state.sessionId},timeout:8000});const id=d.run.id;state.currentJsRunId=id;const started=Date.now();while(Date.now()-started<6*60*1000){if(!state.loopEnabled){try{await api(`/api/js-runs/${encodeURIComponent(id)}/cancel`,{method:'POST'})}catch{}throw new Error('用户停止 Agent 循环')}await checkApprovals();const r=(await api(`/api/js-runs/${encodeURIComponent(id)}`,{timeout:4000})).run;patchEvent(ev.id,{status:r.status==='completed'?'ok':['failed','cancelled'].includes(r.status)?'err':'run',meta:r.status==='waiting_approval'?'等待用户审批':`本地 Agent · ${r.status}`,output:r.status==='completed'?r.output:(r.error||code.slice(0,1200))});if(['completed','failed','cancelled'].includes(r.status)){state.currentJsRunId=null;return {code,result:{success:r.status==='completed',output:r.output,error:r.error,status:r.status}}}await new Promise(r=>setTimeout(r,350))}throw new Error('等待 JS 执行超时')}
function combinedResultMessage(results){const sep='\n';let msg=`【Relay Agent 执行结果汇总】(共 ${results.length} 个脚本)${sep}${sep}`;results.forEach((item,i)=>{msg+=`—— 脚本 ${i+1} ——${sep}`;if(item.result.success){let out=String(item.result.output||'').trim();if(out.length>15000)out=out.slice(0,15000)+sep+'...[输出过长已截断]...';msg+='✅ 成功'+sep+(out||'(脚本执行完成，无输出)')}else{msg+='❌ 失败'+sep+'错误原因: '+(item.result.error||'未知错误')+sep+'请修正 JavaScript 后重新输出完整的 ```cuckoo 代码块。'}msg+=sep+sep});return msg;}
async function executeCuckooBlocks(blocks,responseKey){if(state.loopBusy||!state.loopEnabled)return;state.loopBusy=true;setStatus();try{if(++state.loopSteps>CFG.maxLoopSteps)throw new Error('达到最大工具循环步数');state.processedResponses.add(responseKey);await recordSession('assistant/cuckoo_blocks',{count:blocks.length});const results=[];for(let i=0;i<blocks.length;i++)results.push(await startJsRun(blocks[i],i+1,blocks.length));await recordSession('tool/cuckoo_results',results.map(x=>x.result));if(state.loopEnabled)await sendDeepSeek(combinedResultMessage(results))}catch(e){log('Relay 工具循环: '+e.message,'err');toast(e.message,'err')}finally{state.loopBusy=false;setStatus()}}

async function processAssistant(){if(!state.loopEnabled||state.loopBusy)return;const snap=latestStableAssistant();if(!snap)return;if(state.processedResponses.has(snap.key))return;const pres=cuckooPres(snap.node),blocks=extractCuckooBlocks(snap.node);if(pres.length&&blocks.length!==pres.length){if(Date.now()-state.lastChangedAt<3600)return;state.processedResponses.add(snap.key);await sendDeepSeek('【Relay 解析错误】检测到不完整或语法错误的 ```cuckoo JavaScript 代码块。请重新输出完整、可执行的 cuckoo 代码块，代码块外不要写文字。');addEvent('system','cuckoo 代码块语法不完整','已要求 AI 重新输出','','err');return}if(blocks.length){state.xmlHintCount=0;await executeCuckooBlocks(blocks,snap.key);return}const jt=parseJsonToolCall(snap.text);if(jt){state.xmlHintCount=0;await executeJsonToolCall(jt,snap.key);return}if(detectXmlToolCall(snap.text)){state.processedResponses.add(snap.key);if(state.xmlHintCount<3){state.xmlHintCount++;await sendDeepSeek('请使用```cuckoo```代码块进行工具调用，而不是 XML / DSML 格式（例如 <｜｜DSML｜｜invoke> 或 <invoke name="...">）。需要工具时只输出 cuckoo JavaScript 代码块，代码块外不要写文字。');addEvent('system',`检测到 XML/DSML 工具调用`,`已提示 AI 改用 cuckoo · ${state.xmlHintCount}/3`,snap.text.slice(0,500),'err')}else addEvent('system','XML/DSML 提示已熔断','连续 3 次后停止自动提示，避免循环','','err');return}state.processedResponses.add(snap.key);if(state.activeWebChat&&snap.count>state.activeWebChat.beforeCount){const chat=state.activeWebChat;state.activeWebChat=null;try{await api(`/api/web/chat/${encodeURIComponent(chat.id)}/reply`,{method:'POST',body:{reply:snap.text},timeout:5000});addEvent('bridge','DeepSeek → 终端','最终回答已返回',snap.text.slice(0,500),'ok')}catch(e){log('回传终端失败: '+e.message,'err')}finally{state.webBridgeBusy=false;setStatus()}}}
function observeReplies(){const ob=new MutationObserver(()=>{clearTimeout(state.scanTimer);state.scanTimer=setTimeout(()=>processAssistant().catch(e=>log(e.message,'err')),300)});ob.observe(document.body,{childList:true,subtree:true,characterData:true});setInterval(()=>processAssistant().catch(()=>{}),650)}

async function initializeDeepSeek(){if(!state.authenticated)throw new Error('请先连接并认证本地 Agent');const d=await api('/api/relay/prompt',{timeout:5000});state.initialized=true;state.loopEnabled=true;state.loopSteps=0;await recordSession('web/protocol',{protocol:d.protocol||'cuckoo-js-v1'});await sendDeepSeek(d.prompt);addEvent('system','Relay 协议已初始化','AI 将输出 ```cuckoo JavaScript','','ok');render();}
async function handleWebBridgeChat(chat){if(state.webBridgeBusy)return;state.webBridgeBusy=true;setStatus();try{await api(`/api/web/chat/${encodeURIComponent(chat.id)}/claim`,{method:'POST',body:{clientId:state.webClientId},timeout:3000});const before=assistantNodes().length;let prompt=String(chat.prompt||'');if(!state.initialized){const d=await api('/api/relay/prompt');state.initialized=true;state.loopEnabled=true;state.loopSteps=0;prompt=d.prompt+'\n\n---\n\n现在处理来自 Relay Agent 终端的用户请求：\n'+prompt}state.activeWebChat={id:chat.id,beforeCount:before};addEvent('bridge','终端 → DeepSeek','网页桥请求',String(chat.prompt||'').slice(0,500),'run');await sendDeepSeek(prompt)}catch(e){state.activeWebChat=null;state.webBridgeBusy=false;try{await api(`/api/web/chat/${encodeURIComponent(chat.id)}/reply`,{method:'POST',body:{error:e.message},timeout:5000})}catch{}log('网页桥: '+e.message,'err')}finally{setStatus()}}
async function pollWebBridge(){if(!state.authenticated||state.webBridgeBusy)return;try{await heartbeatBridge();const d=await api('/api/web/inbox',{timeout:3000});state.webBridgeQueued=(d.chats||[]).length;const c=(d.chats||[])[0];if(c)await handleWebBridgeChat(c)}catch{state.webBridgeOnline=false}}
function startWebBridge(){setInterval(()=>pollWebBridge().catch(()=>{}),900);setInterval(()=>heartbeatBridge().catch(()=>{state.webBridgeOnline=false}),4000)}

function renderTimeline(){if(!state.timeline.length)return `<div class="cuckoo-card"><b>运行时间线</b><div class="cuckoo-muted" style="margin-top:4px">初始化后，检测到的 cuckoo 脚本、审批和执行结果都会显示在这里。</div></div>`;return state.timeline.slice().reverse().map(e=>`<div class="cuckoo-event"><div class="cuckoo-eventline"><i class="cuckoo-eventdot ${e.status||''}"></i></div><div class="cuckoo-eventbody"><div class="cuckoo-spread"><span class="cuckoo-eventtitle">${esc(e.title)}</span><span class="cuckoo-pill ${e.status==='ok'?'green':e.status==='run'?'amber':e.status==='err'?'red':''}">${esc(e.status||e.kind)}</span></div>${e.meta?`<div class="cuckoo-eventmeta">${esc(e.meta)}</div>`:''}${e.output?`<div class="cuckoo-eventout">${esc(e.output)}</div>`:''}</div></div>`).join('')}
function renderConnectionCard(){const reach=state.reachable?'<span class="cuckoo-strong-ok">● 可达</span>':'<span class="cuckoo-strong-err">● 不可达</span>';const auth=state.authenticated?'<span class="cuckoo-strong-ok">● 已认证</span>':state.reachable?'<span class="cuckoo-strong-warn">● 未认证</span>':'<span class="cuckoo-strong-err">● 未连接</span>';return `<div class="cuckoo-card"><div class="cuckoo-spread"><div><b>本地 Agent 连接状态</b><div class="cuckoo-muted">两个状态都正常，才代表网页真的连接了本地执行器。</div></div><button id="cuckoo-refresh" class="cuckoo-btn">立即检测</button></div><div class="cuckoo-diag" style="margin-top:11px"><div class="k">后台服务</div><div class="v">${reach}</div><div class="k">API 鉴权</div><div class="v">${auth}</div><div class="k">DeepSeek 网页桥</div><div class="v">${state.webBridgeOnline?'<span class="cuckoo-strong-ok">● 在线</span>':'<span class="cuckoo-strong-warn">● 未注册</span>'}</div><div class="k">cuckoo 协议</div><div class="v">${state.initialized?'<span class="cuckoo-strong-ok">● 已初始化</span>':'未初始化'}</div><div class="k">Agent 版本</div><div class="v">${esc(state.agentVersion)} / PID ${esc(state.agentPid||'-')}</div><div class="k">项目目录</div><div class="v">${esc(state.projectRoot||'未设置')}</div><div class="k">传输</div><div class="v">${esc(state.transport)} · ${state.latencyMs==null?'-':esc(state.latencyMs+' ms')}</div><div class="k">发送节流</div><div class="v">随机 2～4 秒 · 队列 ${state.sendQueued}</div><div class="k">诊断</div><div class="v ${state.lastError?'cuckoo-strong-warn':''}">${esc(state.lastError||'正常')}</div></div></div>`}
async function renderProject(){if(!state.authenticated)return '<div class="cuckoo-card">请先连接本地 Agent。</div>';let cfg={};try{cfg=(await api('/api/config')).config||{}}catch{}if(!cfg.projectRoot)return '<div class="cuckoo-card">尚未设置项目目录。请到“设置”中填写绝对路径，或双击 agent.command 选择 10。</div>';let items=[];try{const d=await api('/api/execute',{method:'POST',body:{tool:'file_list',arguments:{path:'.'},sessionId:state.sessionId},timeout:5000});items=d.call?.result||[]}catch{}return `<div class="cuckoo-card"><b>${esc(cfg.projectRoot)}</b><div class="cuckoo-muted">所有 AI 文件操作都由本地 Agent 在此根目录内执行；网页不直接修改文件。</div></div><div class="cuckoo-card">${Array.isArray(items)?items.slice(0,200).map(x=>`<div class="cuckoo-file"><span>${x.kind==='directory'?'▸':'·'} ${esc(x.name)}</span><span class="cuckoo-muted">${esc(x.kind)}</span></div>`).join(''):'无法读取目录'}</div>`}
async function render(){const v=$('cuckoo-view');if(!v)return;document.querySelectorAll('.cuckoo-nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));if(state.tab==='agent'){setHeader('Relay Agent',`${state.authenticated?'本地运行时已连接':'本地运行时未连接'} · cuckoo JavaScript`);v.innerHTML=renderConnectionCard()+`<div class="cuckoo-card"><div class="cuckoo-spread"><div><b>DeepSeek → cuckoo 协议 → Relay Agent</b><div class="cuckoo-muted">AI 输出 JavaScript 代码块 → Agent 沙箱执行 → 结果自动回传 AI</div></div><div class="cuckoo-row"><button id="cuckoo-init" class="cuckoo-btn primary">初始化 Relay</button><button id="cuckoo-stop" class="cuckoo-btn danger" ${!state.loopBusy?'disabled':''}>停止</button></div></div></div><div class="cuckoo-section-title">运行时间线</div>${renderTimeline()}`}
else if(state.tab==='files'){setHeader('项目','本地 Agent 项目根目录');v.innerHTML=await renderProject()}
else if(state.tab==='tools'){setHeader('工具','cuckoo JavaScript API');const apis=['readFile(path)','readFileWithLines(path)','read(path, options)','readLines(path, options)','write(path, content)','writeFile(path, content)','edit(path, old, new, replaceAll?, dryRun?)','glob(pattern, path?)','grep(pattern, options?)','bash(command, options?)','webSearch(query, maxResults?)','webLooking(url, options?)','webHtml(url, options?)','webDownload(url, path?, options?)','deleteFile(path)','skill(name, args?)','mcpListServers()','mcpGetTools(server)','mcpCall(server, tool, args?)','terminalStart(command, options?)','terminalWrite(id, data)','terminalStop(id)'];v.innerHTML=`<div class="cuckoo-card"><div class="cuckoo-muted">这些函数只存在于 Agent 的受限 cuckoo JS 环境。DeepSeek 网页本身拿不到 Node.js、fs、process 或 require。</div></div>${apis.map(x=>`<div class="cuckoo-card"><b>${esc(x)}</b></div>`).join('')}`}
else if(state.tab==='plugins'){setHeader('插件','~/.relay-agent/plugins');v.innerHTML=`<div class="cuckoo-card"><div class="cuckoo-spread"><div><b>已加载 ${state.plugins.length} 个插件</b><div class="cuckoo-muted">通过 skill(name,args) 调用；默认需要审批。</div></div><button id="cuckoo-reload-plugins" class="cuckoo-btn">重新加载</button></div></div>${state.plugins.map(p=>`<div class="cuckoo-card"><b>${esc(p.name)}</b><div class="cuckoo-muted">${esc(p.description||p.file||'')}</div></div>`).join('')||'<div class="cuckoo-muted">暂无插件</div>'}`}
else if(state.tab==='logs'){setHeader('日志',`${state.logs.length} 条`);v.innerHTML=`<div class="cuckoo-card">${state.logs.slice().reverse().map(x=>`<div class="cuckoo-log ${x.type}">[${esc(x.t)}] ${esc(x.msg)}</div>`).join('')||'<div class="cuckoo-muted">暂无日志</div>'}</div>`}
else if(state.tab==='settings'){setHeader('设置','连接、项目目录与权限');let cfg={};if(state.authenticated)try{cfg=(await api('/api/config')).config||{}}catch{}v.innerHTML=renderConnectionCard()+`<div class="cuckoo-section-title">连接</div><div class="cuckoo-card"><label class="cuckoo-muted">API 地址</label><input id="cuckoo-api-base" class="cuckoo-input" value="${esc(state.apiBase)}"><div style="height:7px"></div><label class="cuckoo-muted">本机 Agent API Key</label><input id="cuckoo-api-key" class="cuckoo-input" type="password" placeholder="relaykey-...（旧 cckey 也兼容）" value="${esc(state.apiKey)}"><div class="cuckoo-row" style="margin-top:8px"><button id="cuckoo-connect" class="cuckoo-btn primary">保存并连接</button><button id="cuckoo-refresh-settings" class="cuckoo-btn">检测状态</button></div></div><div class="cuckoo-section-title">项目目录</div><div class="cuckoo-card"><input id="cuckoo-project-root" class="cuckoo-input" placeholder="/Users/you/project" value="${esc(cfg.projectRoot||'')}"><div class="cuckoo-row" style="margin-top:8px"><button id="cuckoo-save-project" class="cuckoo-btn">保存项目目录</button></div><div class="cuckoo-muted" style="margin-top:6px">所有相对路径都会基于此目录，且 Agent 会阻止文件工具通过路径或符号链接越界。</div></div><div class="cuckoo-section-title">执行策略</div><div class="cuckoo-card"><div class="cuckoo-spread"><span>当前模式</span><span class="cuckoo-pill amber">${esc(cfg.approvalMode||'ask')}</span></div><div class="cuckoo-row" style="margin-top:9px"><button id="cuckoo-mode-ask" class="cuckoo-btn">需要审批</button><button id="cuckoo-mode-autoall" class="cuckoo-btn primary">全部自动执行</button></div><div class="cuckoo-muted" style="margin-top:7px">“全部自动执行”会自动通过普通审批；系统破坏级硬拒绝规则仍然保留。</div></div>`}bindView();renderFoot()}
function bindView(){const on=(id,fn)=>{const e=$(id);if(e)e.onclick=()=>Promise.resolve(fn()).catch(x=>{toast(x.message,'err');log(x.message,'err')})};on('cuckoo-init',initializeDeepSeek);on('cuckoo-stop',stopLoop);on('cuckoo-reload-plugins',async()=>{await api('/api/plugins/reload',{method:'POST'});await refreshAgent();render();toast('插件已重新加载','ok')});on('cuckoo-connect',async()=>{state.apiBase=$('cuckoo-api-base').value.trim()||CFG.apiBase;state.apiKey=$('cuckoo-api-key').value.trim();localStorage.setItem(SKEY.api,state.apiBase);sessionStorage.setItem(SKEY.key,state.apiKey);await refreshAgent(false);render()});on('cuckoo-refresh',()=>refreshAgent(false).then(render));on('cuckoo-refresh-settings',()=>refreshAgent(false).then(render));on('cuckoo-save-project',async()=>{const p=$('cuckoo-project-root').value.trim();await api('/api/config',{method:'PUT',body:{projectRoot:p}});toast('项目目录已更新','ok');await refreshAgent();render()});on('cuckoo-mode-ask',async()=>{await api('/api/config',{method:'PUT',body:{approvalMode:'ask'}});toast('已切换为需要审批');await refreshAgent();render()});on('cuckoo-mode-autoall',async()=>{await api('/api/config',{method:'PUT',body:{approvalMode:'auto_all'}});toast('已开启全部自动执行','ok');await refreshAgent();render()})}
async function stopLoop(){state.loopEnabled=false;if(state.currentJsRunId)try{await api(`/api/js-runs/${encodeURIComponent(state.currentJsRunId)}/cancel`,{method:'POST'})}catch{}state.loopBusy=false;state.currentJsRunId=null;setStatus();toast('Relay 工具循环已停止');render()}
function drag(){const fab=$('cuckoo-fab'),panel=$('cuckoo-panel');let sx=0,sy=0,sl=0,st=0,moved=false,raf=0;const updatePanel=()=>{const r=fab.getBoundingClientRect(),pw=panel.offsetWidth,ph=panel.offsetHeight,g=12;let l=r.right-pw,t=r.top-ph-g;if(t<8)t=r.bottom+g;if(l<8)l=r.left-pw-g;l=Math.max(8,Math.min(innerWidth-pw-8,l));t=Math.max(8,Math.min(innerHeight-ph-8,t));panel.style.left=l+'px';panel.style.top=t+'px'};fab.onpointerdown=e=>{fab.setPointerCapture(e.pointerId);const r=fab.getBoundingClientRect();sx=e.clientX;sy=e.clientY;sl=r.left;st=r.top;moved=false};fab.onpointermove=e=>{if(!fab.hasPointerCapture(e.pointerId))return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.hypot(dx,dy)>3)moved=true;const l=Math.max(4,Math.min(innerWidth-fab.offsetWidth-4,sl+dx)),t=Math.max(4,Math.min(innerHeight-fab.offsetHeight-4,st+dy));fab.style.left=l+'px';fab.style.top=t+'px';fab.style.right='auto';fab.style.bottom='auto';localStorage.setItem(SKEY.x,l);localStorage.setItem(SKEY.y,t);cancelAnimationFrame(raf);raf=requestAnimationFrame(updatePanel)};fab.onpointerup=e=>{try{fab.releasePointerCapture(e.pointerId)}catch{}if(!moved){state.open=!state.open;panel.classList.toggle('hide',!state.open);if(state.open)updatePanel()}};const x=+localStorage.getItem(SKEY.x),y=+localStorage.getItem(SKEY.y);if(Number.isFinite(x)&&x>0){fab.style.left=Math.min(x,innerWidth-62)+'px';fab.style.right='auto'}if(Number.isFinite(y)&&y>0){fab.style.top=Math.min(y,innerHeight-62)+'px';fab.style.bottom='auto'}const w=Math.max(420,+localStorage.getItem(SKEY.w)||CFG.panelW),h=Math.max(420,+localStorage.getItem(SKEY.h)||CFG.panelH);panel.style.width=Math.min(w,innerWidth-16)+'px';panel.style.height=Math.min(h,innerHeight-16)+'px';const rz=$('cuckoo-resize');let rw,rh,rx,ry;rz.onpointerdown=e=>{e.preventDefault();rz.setPointerCapture(e.pointerId);rw=panel.offsetWidth;rh=panel.offsetHeight;rx=e.clientX;ry=e.clientY};rz.onpointermove=e=>{if(!rz.hasPointerCapture(e.pointerId))return;const nw=Math.max(420,Math.min(innerWidth-16,rw+e.clientX-rx)),nh=Math.max(420,Math.min(innerHeight-16,rh+e.clientY-ry));panel.style.width=nw+'px';panel.style.height=nh+'px';localStorage.setItem(SKEY.w,nw);localStorage.setItem(SKEY.h,nh);updatePanel()};rz.onpointerup=e=>{try{rz.releasePointerCapture(e.pointerId)}catch{}};setTimeout(updatePanel,50);window.addEventListener('resize',updatePanel)}
function bindGlobal(){document.querySelectorAll('.cuckoo-nav').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});$('cuckoo-modal-deny').onclick=()=>closeApproval('deny');$('cuckoo-modal-once').onclick=()=>closeApproval('allow_once');$('cuckoo-modal-trust').onclick=()=>closeApproval('trust_exact');document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.open){state.open=false;$('cuckoo-panel').classList.add('hide')}if(e.ctrlKey&&e.shiftKey&&e.code==='KeyC'){e.preventDefault();state.open=!state.open;$('cuckoo-panel').classList.toggle('hide',!state.open)}})}
async function init(){inject();drag();bindGlobal();observeReplies();startWebBridge();await refreshAgent(true);setStatus();await render();setInterval(()=>refreshAgent(true),10000);setInterval(()=>checkApprovals().catch(()=>{}),650);log('Relay Agent v0.7.0 已就绪','ok')}
window.__RELAY_V7_TEST__={extractCuckooBlocks,getCodeBlockLanguage,syntaxComplete,detectXmlToolCall,parseJsonToolCall};
setTimeout(()=>init().catch(e=>console.error('[Relay]',e)),500);
})();
